### PR TITLE
Mattis

### PR DESCRIPTION
**Pull request by LinguList**
@ilchec, please check what I did here carefully! I added a script called "lexibank_chechuroborrowing.py", and also a script to install the data `setup.py`. 

Now, please do exactly as follows:

1. make a fresh virtual environment
2. git pull
3. git checkout mattis
4. pip install -e ./ (when having cded into the folder chechuroborrowing)
5. cldfbench lexibank.makecldf chechuroborrowing

This will re-run all the code and create the CLDF data.

After you have done this, you can merge this PR.

For the two other datasets, please pay attention to the modifications, especially of the data in `etc` and sources (I hate it to correct other peoples missing brackets in bibtex files...).

### CODE REVIEW

**Comment by ilchec** [comment]
@LinguList Is it OK that I get this warning for every single line of forms.csv?

WARNING forms.csv:2:Source missing source key: Arkhit1

**Comment by LinguList** [comment]
Nope, it means you have provided some bad source there. Did you modify
the code? I think your bibtex key is not matching with the data in
languages.tsv ...

**Comment by ilchec** [comment]
No, I didn't. Got it, I'll check the bibtex! Thanks!

**Comment by ilchec** [comment]
@LinguList Okay, it took me some time to figure out what's wrong, but it looks like I made it work. I needed to change the code a little and fix sources.bib and the source column in the data. I pushed everything into the new _mattis_cldf_ branch, in case I did something wrong, pls check.

**Review by LinguList — COMMENTED** [review]
So what CODE did you change? I don't see any differences here. But good that you added the sources for the languages!

**Comment by LinguList** [comment]
Feel free to merge now!

**Comment by ilchec** [comment]
Answering your question:
Line 74 is now                    Source=row['Source']
Line 80 is now                     Source=row['Source']

OK, I'll merge the new branch with master

**Comment by LinguList** [comment]
Yes, that was wrong, but you should modify it as this:


```

Source=sources[row['Code']]

```


And you should NOT do this in the second case, where `chechuro2021` is
still the correct key!

**Comment by ilchec** [comment]
Oh, Okay, I see, I'll fix the first one. But it didn't work with "chechuro2021", this is why I got those warning messages because it couldn't map it to anything on the bibtex. Also Persian, Arabic and Azerbaijani come from experts, I cite them as PC. I checked the output and it looks correct to me, but I may be wrong. The entries in cognates.csv are now linked to the proper sources of data, not just to me.

**Comment by ilchec** [comment]
Oh wait, I am wrong! It did work, but it mapped wrong sources: I am not the source of ALL data, some data come from experts. I needed to put bulakhpc, suleymanovpc and armandpc there. If I just put chechurofielddata (I renamed chechuro2021), it'd be wrong, I guess.

**Pull request merged**
